name: Publish Release Package
on:
  push:
    branches:
      - 'release'

env:
  DOTNET_VERSION: '5.0.x'

jobs:
  build:
    name: Publish Release Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
      - name: Pack for Publishing
        run: dotnet pack --configuration Release
      - name: Publish Release Package
        run: dotnet nuget push src/bin/Release/*.nupkg --api-key ${{secrets.CI_PUBLISH_PKG_PAT}} --source https://nuget.pkg.github.com/cmiles74/index.json --skip-duplicate
      - name: Publish Release Package to NuGet
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/Nervestaple.WebService.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          TAG_COMMIT: false